name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run build.sh
      run: |
        echo "Hello world" > a.txt
    - name: Upload a.txt
      uses: actions/upload-artifact@v1
      with:
        name: a.txt
        path: a.txt
    - name: Upload a.txt
      uses: actions/upload-artifact@v1
      with:
        name: setup.iss
        path: setup.iss
        
  windows:
    name: Build Windows 64bit installer
    needs: build
    runs-on: windows
    steps:
      - name: Download a.txt
        uses: actions/download-artifact@v1
        with:
          name: a.txt
          path: .
      - name: Create installer
        shell: bash
        run: |
          iscc setup.iss
      - name: Upload 64bit installer
        uses: actions/upload-artifact@v1
        with:
          name: 64bit
          path: Output
